---
- hosts: all
  gather_facts: no
  connection: local
  # The pre_tasks section is only added to check that all
  # the prereqs to run this playbook work. It is not a required
  # thing to do. IT IS OPTIONAL but helpful for the demonstration
  pre_tasks:
    - include_tasks: preflight_checks.yml
  tasks:
    - name: DEMOTASK - create an address object
      panos_object:
        ip_address: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        operation: add
        address: "{{ lookup('dig', newhost) }}"
        address_type: ip-netmask
        addressobject: "{{ newhost }}"
